### ISSUE TITLE
is it suitable for cpu cluster?

### ISSUE THREAD

**Issue by fancyerii** [uoguelph-mlrg/Theano-MPI#16]
I have a cpu cluster with dozens of nodes with a few cpu cores, is it suitable to use theano-mpi to speed up training?

**Comment by hma02** [comment]
Hi @fancyerii 

Yes, you can. You can program in theano and run your code on cpu

**Comment by powerreactor** [comment]
Hi @hma02 

Better to test it by ourselves first. We have cuda memcpy and other cuda functions before allreduce.

**Comment by hma02** [comment]
@powerreactor 

Right. Since the current parallel loading method is based on cuda memcpy to set shared_x to GPU, we might need to figure out how to do parallel loading for CPU only implementation. I think a possible way is use the posix_ipc, something like [here](https://github.com/mila-udem/platoon/blob/master/platoon/channel.py#L336). Do you have any suggestions?

I will turn off parallel loading and have a try.

**Comment by powerreactor** [comment]
@hma02 I would suggest to use GPU ONLY

**Comment by powerreactor** [comment]
New backend supports only GPUs. Close this issue.
